#ifndef defines_h_
#define defines_h_

#define SETBIT(WORD,BITPOS) (WORD|=1<<BITPOS)
#define CLRBIT(WORD,BITPOS) (WORD&=~(1<<BITPOS))

#define SSETBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define SCLRBIT(WORD,BITPOS) (WORD=1<<BITPOS)
#define CPLBIT(WORD,BITPOS) (WORD^=1<<BITPOS)

#define WBYTE(WORD,SETPOS,BYTE) (WORD=(WORD&~(0XFF<<SETPOS))|(BYTE<<SETPOS))
#define WNIBBLE(WORD,SETPOS,NIBBLE) WORD=(WORD&~(0XF<<SETPOS))|(NIBBLE<<SETPOS)

#define WBIT(WORD,BITPOS,BIT) (WORD=(WORD&~(1<<BITPOS))|(BIT<<BITPOS))
#define RBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define RNIBBLE(WORD,SETPOS) ((WORD>>SETPOS)&15)
#define RBYTE(WORD,SETPOS) ((WORD>>SETPOS)&255)
#define READWRITEBIT(DWORD,DBIT,SBIT) DWORD=(DWORD&~(1<<DBIT))|(((DWORD>>SBIT)&1)<<DBIT)
#define READWRITEBIT2(DWORD,DBIT,SWORD,SBIT) DWORD=(DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT)
#endif

